name: flutter_commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  commercio_ui:
  #  git:
  #    url: https://github.com/commercionetwork/CommercioUI.git
  #    path: packages/commercio_ui
  #    ref: dev
    path: ../commercio_ui
  basic_utils: ">=3.0.0 <4.0.0"
  bloc: '>=7.0.0 <8.0.0'
  equatable: '>=2.0.0 <3.0.0'
  flutter_bloc: '>=7.0.0 <8.0.0'
  flutter_secure_storage: '>=4.0.0 <5.0.0'
  freezed_annotation: ">=0.14.0 <0.15.0"
  http: ">=0.13.0 <0.14.0"
  shared_preferences: ">=2.0.0 <3.0.0"
  #shared_preferences_linux: ">=0.0.2 <0.1.0"
  #shared_preferences_macos: ">=0.0.1 <0.1.0"
  #shared_preferences_web: ">=0.1.0 <2.0.0"
  uuid: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=2.0.0 <3.0.0"
  freezed: ">=0.14.0 <0.15.0"
  json_serializable: ">=4.0.0 <6.0.0"
  mocktail: ">=0.1.0 <0.2.0"
  flutter_lints: ">=1.0.0 <2.0.0"
