import 'package:flutter/material.dart';
import 'package:flutter_commercio_ui/flutter_commercio_ui.dart';

class DeriveDocumentTextField extends CommercioTextField<
    CommercioDocsDeriveDocumentBloc,
    CommercioDocsDeriveDocumentEvent,
    CommercioDocsDeriveDocumentState,
    CommercioDocsDeriveDocumentStateInitial,
    CommercioDocsDeriveDocumentStateData,
    CommercioDocsDeriveDocumentStateLoading,
    CommercioDocsDeriveDocumentStateError> {
  DeriveDocumentTextField({
    required String Function(
            BuildContext context, CommercioDocsDeriveDocumentState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class ShareDocumentsTextField extends CommercioTextField<
    CommercioDocsShareDocumentsBloc,
    CommercioDocsShareDocumentsEvent,
    CommercioDocsSharedDocumentsState,
    CommercioDocsSharedDocumentsStateInitial,
    CommercioDocsSharedDocumentsStateData,
    CommercioDocsSharedDocumentsStateLoading,
    CommercioDocsSharedDocumentsStateError> {
  ShareDocumentsTextField({
    required String Function(
            BuildContext context, CommercioDocsSharedDocumentsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class DeriveReceiptTextField extends CommercioTextField<
    CommercioDocsDeriveReceiptBloc,
    CommercioDocsDeriveReceiptEvent,
    CommercioDocsDeriveReceiptState,
    CommercioDocsDeriveReceiptStateInitial,
    CommercioDocsDeriveReceiptStateData,
    CommercioDocsDeriveReceiptStateLoading,
    CommercioDocsDeriveReceiptStateError> {
  DeriveReceiptTextField({
    required String Function(
            BuildContext context, CommercioDocsDeriveReceiptState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class SendReceiptsTextField extends CommercioTextField<
    CommercioDocsSendReceiptsBloc,
    CommercioDocsSendReceiptsEvent,
    CommercioDocsSentReceiptState,
    CommercioDocsSentReceiptStateInitial,
    CommercioDocsSentReceiptStateData,
    CommercioDocsSentReceiptStateLoading,
    CommercioDocsSentReceiptStateError> {
  SendReceiptsTextField({
    required String Function(
            BuildContext context, CommercioDocsSentReceiptState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class SentDocumentsTextField extends CommercioTextField<
    CommercioDocsSentDocumentsBloc,
    CommercioDocsSentDocumentsEvent,
    CommercioDocsSentDocumentsState,
    CommercioDocsSentDocumentsStateInitial,
    CommercioDocsSentDocumentsStateData,
    CommercioDocsSentDocumentsStateLoading,
    CommercioDocsSentDocumentsStateError> {
  SentDocumentsTextField({
    required String Function(
            BuildContext context, CommercioDocsSentDocumentsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class ReceivedDocumentsTextField extends CommercioTextField<
    CommercioDocsReceivedDocumentsBloc,
    CommercioDocsReceivedDocumentsEvent,
    CommercioDocsReceivedDocumentsState,
    CommercioDocsReceivedDocumentsStateInitial,
    CommercioDocsReceivedDocumentsStateData,
    CommercioDocsReceivedDocumentsStateLoading,
    CommercioDocsReceivedDocumentsStateError> {
  ReceivedDocumentsTextField({
    required String Function(
            BuildContext context, CommercioDocsReceivedDocumentsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class SentReceiptsTextField extends CommercioTextField<
    CommercioDocsSentReceiptsBloc,
    CommercioDocsSentReceiptsEvent,
    CommercioDocsSentReceiptsState,
    CommercioDocsSentReceiptsStateInitial,
    CommercioDocsSentReceiptsStateData,
    CommercioDocsSentReceiptsStateLoading,
    CommercioDocsSentReceiptsStateError> {
  SentReceiptsTextField({
    required String Function(
            BuildContext context, CommercioDocsSentReceiptsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class ReceivedReceiptsTextField extends CommercioTextField<
    CommercioDocsReceivedReceiptsBloc,
    CommercioDocsReceivedReceiptsEvent,
    CommercioDocsReceivedReceiptsState,
    CommercioDocsReceivedReceiptsStateInitial,
    CommercioDocsReceivedReceiptsStateData,
    CommercioDocsReceivedReceiptsStateLoading,
    CommercioDocsReceivedReceiptsStateError> {
  ReceivedReceiptsTextField({
    required String Function(
            BuildContext context, CommercioDocsReceivedReceiptsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}
