name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI/packages/commercio_ui

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  commerciosdk: ">=2.2.0 <2.3.0"
  equatable: ">=2.0.0 <3.0.0"
  freezed_annotation: ">=0.14.0 <0.15.0"
  http: ">=0.13.0 <0.14.0"
  uuid: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ">=2.0.0 <3.0.0"
  freezed: ">=0.14.2 <0.15.0"
  json_serializable: ">=5.0.0 <6.0.0"
  mocktail: ">=0.1.0 <0.2.0"
  flutter_lints: ">=1.0.0 <2.0.0"
  test: ">=1.17.0 <2.0.0"
