name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI/packages/commercio_ui

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  commerciosdk: ">=2.2.0 <2.3.0"
  equatable: ">=2.0.0 <3.0.0"
  freezed_annotation: ">=0.14.1 <0.15.0"
  http: '>=0.13.0 <0.14.0'
  uuid: ">=3.0.2 <4.0.0"

dev_dependencies:
  build_runner: '>=1.12.0 <1.13.0'
  freezed: ">=0.14.0 <0.15.0"
  json_serializable: ">=4.0.0 <5.0.0"
  mockito: ">=5.0.0 <6.0.0"
  pedantic: ">=1.11.0 <1.12.0"
  test: ">=1.16.0 <1.17.0"
