name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI/packages/commercio_ui

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  basic_utils: ^2.6.3
  bip39: '>=1.0.3 <1.1.0'
  commerciosdk: ^2.1.3
  equatable: '>=1.2.5 <1.3.0'
  freezed_annotation: ^0.12.0
  http: '>=0.12.2 <0.13.0'
  sacco: ^0.1.5
  uuid: ^2.2.2

dev_dependencies:
  build_runner: '>=1.10.2 <1.11.0'
  freezed: ^0.12.2
  json_serializable: '>=3.3.0 <3.6.0'
  mockito:
  pedantic: '>=1.9.2 <1.10.0'
  test: '>=1.15.7 <1.16.0'
