os:
    - linux
sudo: false
addons:
    apt:
        # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
        sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
        packages:
            - libstdc++6
before_script:
    - git clone https://github.com/flutter/flutter.git -b stable --depth 1
    - export FLUTTER_ROOT=./flutter
    - export PATH="$PATH:`pwd`./flutter/bin"
    - export PATH="$PATH:`pwd`./flutter/bin/cache/dart-sdk/bin"
    - flutter doctor
script:
    - flutter pub get
    - flutter analyze --no-pub lib/
    - flutter format -n --set-exit-if-changed lib/
    - flutter test
cache:
    directories:
        - $HOME/.pub-cache
