name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^2.6.3
  bip39: '>=1.0.3 <1.1.0'
  bloc: ^6.1.0
  commerciosdk: ^2.1.3
  equatable: '>=1.2.5 <1.3.0'
  flutter_bloc: ^6.0.6
  flutter_secure_storage: '>=3.3.5 <3.4.0'
  freezed_annotation: ^0.12.0
  http: '>=0.12.2 <0.13.0'
  sacco: ^0.1.5
  shared_preferences: ^0.5.12
  shared_preferences_linux: ">=0.0.2 <0.1.0"
  shared_preferences_macos: ">=0.0.1 <0.1.0"
  shared_preferences_web: ">=0.1.0 <2.0.0"
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=1.10.2 <1.11.0'
  freezed: ^0.12.2
  json_serializable: '>=3.3.0 <3.6.0'
  mockito: ^4.1.3
  pedantic: '>=1.9.2 <1.10.0'
  test_coverage: '>=0.4.0 <0.6.0'

flutter:
