name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.2.0
homepage: https://github.com/commercionetwork/CommercioUI

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^2.5.5
  bip39: ^1.0.3
  bloc: ^6.0.0-dev.1
  commerciosdk:
    git:
      url: https://github.com/pasqenr/commercio-sdk.dart.git
      ref: master
  equatable: ^1.2.2
  flutter_bloc: ^6.0.0-dev.1
  flutter_secure_storage: ^3.3.3
  freezed_annotation: ^0.11.0
  http: ^0.12.1
  sacco:
    git:
      url: https://github.com/pasqenr/sacco.dart
      ref: master
  shared_preferences: ^0.5.8
  shared_preferences_web: ">=0.1.0 <2.0.0"
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.2
  json_serializable: ^3.3.0
  lint: ^1.2.0
  mockito: ^4.1.1
  test: ^1.14.4
  test_coverage: ^0.4.3

flutter:
