name: commercio_ui
description: CommercioUI pre-build clean Core+UI widgets intended to reduce significantly the overall blockchain app development time
version: 0.0.3
homepage: https://github.com/commercionetwork/CommercioUI

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^2.5.4
  bip39: ^1.0.3
  bloc: ^5.0.0
  commerciosdk:
    git:
      url: https://github.com/pasqenr/commercio-sdk.dart.git
      ref: master
  equatable: ^1.2.0
  flutter_bloc: ^5.0.0
  flutter_secure_storage: ^3.3.3
  freezed_annotation: ^0.11.0
  http: ^0.12.1
  meta: ^1.1.8
  sacco:
    git:
      url: https://github.com/pasqenr/sacco.dart
      ref: master
  shared_preferences: ^0.5.7+3
  shared_preferences_web: ">=0.1.0 <2.0.0"
  uuid: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.11.2
  lint: ^1.2.0
  mockito: ^4.1.1
  test: ^1.14.4
  test_coverage: ^0.4.3
  json_serializable: ^3.3.0

flutter:
