import 'package:flutter/material.dart';
import 'package:flutter_commercio_ui/flutter_commercio_ui.dart';

class GenerateKeysTextField extends CommercioTextField<
    CommercioIdGenerateKeysBloc,
    CommercioIdGenerateKeysEvent,
    CommercioIdGeneratedKeysState,
    CommercioIdGeneratedKeysStateInitial,
    CommercioIdGeneratedKeysStateData,
    CommercioIdGeneratedKeysStateLoading,
    CommercioIdGeneratedKeysStateError> {
  GenerateKeysTextField({
    required String Function(
            BuildContext context, CommercioIdGeneratedKeysState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class RestoreKeysTextField extends CommercioTextField<
    CommercioIdRestoreKeysBloc,
    CommercioIdRestoreKeysEvent,
    CommercioIdRestoredKeysState,
    CommercioIdRestoredKeysStateInitial,
    CommercioIdRestoredKeysStateData,
    CommercioIdRestoredKeysStateLoading,
    CommercioIdRestoredKeysStateError> {
  RestoreKeysTextField({
    required String Function(
            BuildContext context, CommercioIdRestoredKeysState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class DeleteKeysTextField extends CommercioTextField<
    CommercioIdDeleteKeysBloc,
    CommercioIdDeleteKeysEvent,
    CommercioIdDeletedKeysState,
    CommercioIdDeletedKeysStateInitial,
    CommercioIdDeletedKeysStateData,
    CommercioIdDeletedKeysStateLoading,
    CommercioIdDeletedKeysStateError> {
  DeleteKeysTextField({
    required String Function(
            BuildContext context, CommercioIdDeletedKeysState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class DeriveDidDocumentTextField extends CommercioTextField<
    CommercioIdDeriveDidDocumentBloc,
    CommercioIdDeriveDidDocumentEvent,
    CommercioIdDerivedDidDocumentState,
    CommercioIdDerivedDidDocumentStateInitial,
    CommercioIdDerivedDidDocumentStateData,
    CommercioIdDerivedDidDocumentStateLoading,
    CommercioIdDerivedDidDocumentStateError> {
  DeriveDidDocumentTextField({
    required String Function(
            BuildContext context, CommercioIdDerivedDidDocumentState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class SetDidDocumentTextField extends CommercioTextField<
    CommercioIdSetDidDocumentsBloc,
    CommercioIdSetDidDocumentsEvent,
    CommercioIdSetDidDocumentsState,
    CommercioIdSetDidDocumentsStateInitial,
    CommercioIdSetDidDocumentsStateData,
    CommercioIdSetDidDocumentsStateLoading,
    CommercioIdSetDidDocumentsStateError> {
  SetDidDocumentTextField({
    required String Function(
            BuildContext context, CommercioIdSetDidDocumentsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class RechargeTumblerTextField extends CommercioTextField<
    CommercioIdRechargeTumblerBloc,
    CommercioIdRechargeTumblerEvent,
    CommercioIdRechargedTumblerState,
    CommercioIdRechargedTumblerStateInitial,
    CommercioIdRechargedTumblerStateData,
    CommercioIdRechargedTumblerStateLoading,
    CommercioIdRechargedTumblerStateError> {
  RechargeTumblerTextField({
    required String Function(
            BuildContext context, CommercioIdRechargedTumblerState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class DeriveDidPowerUpRequestTextField extends CommercioTextField<
    CommercioIdDeriveDidPowerUpRequestBloc,
    CommercioIdDeriveDidPowerUpRequestEvent,
    CommercioIdDeriveDidPowerUpRequestState,
    CommercioIdDeriveDidPowerUpRequestStateInitial,
    CommercioIdDeriveDidPowerUpRequestStateData,
    CommercioIdDeriveDidPowerUpRequestStateLoading,
    CommercioIdDeriveDidPowerUpRequestStateError> {
  DeriveDidPowerUpRequestTextField({
    required String Function(
            BuildContext context, CommercioIdDeriveDidPowerUpRequestState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}

class RequestDidPowerUpTextField extends CommercioTextField<
    CommercioIdRequestDidPowerUpsBloc,
    CommercioIdRequestDidPowerUpsEvent,
    CommercioIdRequestedDidPowerUpsState,
    CommercioIdRequestedDidPowerUpsStateInitial,
    CommercioIdRequestedDidPowerUpsStateData,
    CommercioIdRequestedDidPowerUpsStateLoading,
    CommercioIdRequestedDidPowerUpsStateError> {
  RequestDidPowerUpTextField({
    required String Function(
            BuildContext context, CommercioIdRequestedDidPowerUpsState state)
        text,
    TextEditingController? controller,
    FocusNode? focusNode,
    bool autofocus = false,
    ValueChanged<String>? onChanged,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onSubmitted,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? enabled,
    VoidCallback? onTap,
    String Function(BuildContext context)? loading,
    String Function(BuildContext context, String errorMessage)? error,
    CommercioTextFieldStyle? textFieldStyle,
    CommercioTextFieldStyle? textFieldLoadingStyle,
    String? restorationId,
    Key? key,
  }) : super(
          key: key,
          text: text,
          autofocus: autofocus,
          controller: controller,
          enabled: enabled,
          error: error,
          focusNode: focusNode,
          loading: loading,
          onAppPrivateCommand: onAppPrivateCommand,
          onChanged: onChanged,
          onEditingComplete: onEditingComplete,
          onSubmitted: onSubmitted,
          onTap: onTap,
          restorationId: restorationId,
          textFieldLoadingStyle: textFieldLoadingStyle,
          textFieldStyle: textFieldStyle,
        );
}
